<div id="messagebody">
    <div class="message-htmlpart" id="message-htmlpart1">
        <div class="rcmBody" style="font-size: 10pt; font-family: Verdana,Geneva,sans-serif">
            <div id="v1forwardbody1">
                <div style="font-size: 12pt; font-family: Helvetica,Arial,sans-serif">
                    <div id="v1v1forwardbody1">
                        <div id="v1v1v1message-content">
                            <div class="v1v1v1rightcol">
                                <div id="v1v1v1messagebody">
                                    <div id="v1v1v1message-htmlpart1" class="v1v1v1message-htmlpart">
                                        <div class="v1v1v1rcmBody" style="font-size: 12pt; font-family: Helvetica,Arial,sans-serif">
                                            <div id="v1v1v1v1forwardbody1">
                                                <div style="font-size: 10pt; font-family: Verdana,Geneva,sans-serif">
                                                    <div id="v1v1v1v1v1forwardbody1">
                                                        <div style="font-size: 10pt; font-family: Verdana,Geneva,sans-serif">
                                                            <p style="text-align: center"><em>Estimad@ participante </em><strong><em><?= $nombre ?></em></strong><br><span style="color: #236fa1"><strong><em>¡Gracias por su registro¡ </em></strong></span><span style="font-size: 10pt"><em>Falta poco para ser parte de nuestro curso-taller en Línea </em><span style="color: #236fa1"><strong><em>"Cómo Desarrollar Artículos Científicos Válidos: Metodología de la Investigación"</em></strong></span></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><img style="display: block; margin-left: auto; margin-right: auto" src="https://redesla.la/cursos/img/Correoimg.jpg" width="425" height="104"></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt">El curso-taller está diseñado para llevarse&nbsp;a cabo&nbsp;los sábados&nbsp;<span style="color: #2dc26b"><strong><span style="color: #236fa1">19, 26 de agosto y 02 de septiembre de</span> <span style="color: #236fa1">2023</span></strong></span><strong>&nbsp;</strong>por medio de sesiones presenciales a distancia y en tiempo real a través de ZOOM con <span style="color: #236fa1"><em>INTERACCIÓN ENTRE INSTRUCTORES Y PARTICIPANTES, ADEMÁS DE RETROALIMENTACIÓN PERSONALIZADA DURANTE TODO EL CURSO-TALLER.</em></span></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><br><span style="font-size: 10pt">Dicho curso-taller se divide en 18 horas presenciales a distancia y en tiempo real a través de ZOOM y 12 horas más con actividades de trabajo en casa mediante la plataforma Moodle de la organización RedesLA<strong>&nbsp;</strong>con un TOTAL de 30HRS.</span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>Horarios&nbsp;del curso-taller por sesión:</strong>&nbsp;</span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt">Las 18 horas presenciales a distancia y en tiempo real a través de ZOOM serán impartidas los días&nbsp;<strong>19, 26 de agosto y 02 de septiembre en el horario de 08:30</strong><strong>&nbsp;</strong><strong>HRS a 14:30 HRS (hora Centro de México).&nbsp;</strong></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt">Deberá trabajar las 12 horas no presenciales mediante las actividades asignadas los días 19, 26 de agosto y 02 de septiembre, dichas actividades serán monitoreadas mediante la plataforma Moodle de la organización RedesLA: <a href="https://moodle.redesla.la/login/" rel="noreferrer" target="_blank">https://moodle.redesla.la/login/</a>.&nbsp;&nbsp;</span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt">Debe respetar las políticas de forma y las fechas de entrega establecidas para que los instructores puedan realizar su revisión de forma <strong>asincrónica</strong>&nbsp;y cumplir con lo requerido para la acreditación del curso.&nbsp;</span></p>
                                                            <p style="text-align: center"><span style="font-size: 10pt"><strong><em>Para seguir con tu&nbsp;inscripción, le pedimos que continúes con los siguientes pasos:</em></strong></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><span style="color: #236fa1"><strong>1.</strong></span> Confirme el esquema de participación con el que desea participar:</span></p>
                                                            <p style="text-align: center"><span style="color: #236fa1; font-size: 10pt"><strong>Paquete C:&nbsp;</strong>Curso-taller en línea "Cómo Desarrollar Artículos Científicos Válidos: Metodología de la Investigación" + Constancia acreditación + <span style="font-size: 10pt">Publicación en Libro Electrónico + Congreso con presentación.</span></span></p>
                                                            <ul>
                                                                <li style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt">Constancia con formato DC-3 "Constancia de competencias o de habilidades laborales" avalada por la Secretaría de Trabajo y Previsión Social.</li>
                                                                <li style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><strong>Retroalimentación</strong> en sus talleres del curso emitido por especialistas de RedesLA.</li>
                                                                <li style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt">Herramientas para la elaboración de un trabajo de investigación que será <strong>publicado en el libro electrónico</strong> del curso-taller, dictaminado a doble ciego por la editorial <a href="https://iquatroeditores.org/revista/index.php/index/index" rel="noreferrer" target="_blank">iQuatro Editores</a> y que contará con <strong>ISBN</strong>.</li>
                                                                <li style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><strong>Colaboración</strong> de hasta 4 autores por trabajo de investigación.</li>
                                                                <li style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>Acceso al</strong>&nbsp;<strong>congreso</strong> de su preferencia de alguna nuestras redes de investigación (RELEP, RELAYN o RELEN).</span><span style="font-size: 10pt"></span></li>
                                                                <li><span style="font-size: 10pt">Presentación de <strong>ponencia</strong> en el congreso elegido de acuerdo a la modalidad de su elección: </span><span style="font-size: 10pt">presencia, remota o grabada.</span><span style="font-size: 10pt"></span></li>
                                                                <li style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>Constancia</strong> de <strong>participación</strong> en el congreso seleccionado.</span></li>
                                                                <li style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>Constancia</strong> de <strong>ponente</strong> dentro del congreso.&nbsp;</span></li>
                                                            </ul>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>Los mejores artículos científicos de Ciencias Administrativas, Ciencias de la Educación y Pedagogía de este curso tendrán la posibilidad de ser publicados en Revista indexada, de acuerdo con el dictamen obtenido en la revisión doble ciego realizado por la editorial iQuatro Editores.</strong></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt">&nbsp;</p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><span style="color: #236fa1"><strong>2.</strong></span> Realice el pago mediante transferencia interbancaria desde su banca móvil a <strong>Grupo REDESLA</strong> con <strong>RFC</strong> GRE230221H2A en la <strong>cuenta bancaria</strong> 65509756427 del <strong>banco SANTANDER</strong> con <strong>CLABE interbancaria</strong> 0146 8565 5097 5642 76 o bien en <strong>depósito</strong> desde <strong>Oxxo</strong> al número de tarjeta 5579 0890 0446 0880.</span></p>
                                                            <p style="text-align: center"><span style="color: #236fa1; font-size: 10pt"><strong>Paquete C:&nbsp;</strong>Curso-taller en línea "Cómo Desarrollar Artículos Científicos Válidos: Metodología de la Investigación" + Constancia acreditación + <span style="font-size: 10pt">Publicación en Libro Electrónico + Congreso con presentación.</span></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt">Cantidad a depositar con&nbsp;<strong>descuento de</strong>&nbsp;<strong>pronto pago hasta el día 17 de julio</strong>&nbsp;del 2023:<strong>$7,950.00 MXN IVA incluido (siete mil novecientos cincuenta pesos 00/100 MXN)</strong>, es indispensable que sea el importe exacto.</span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt">Cantidad a depositar después de la fecha de pronto pago<strong>&nbsp;hasta el día 17 de agosto del 2023</strong>:<strong>$8250.00 MXN IVA incluido (ocho mil doscientos cincuenta pesos 00/100 MXN)</strong>, es indispensable que sea el importe exacto.</span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><span style="color: #236fa1"><strong>3.</strong> </span>Envíe el comprobante/fotografía por correo electrónico a <strong>pmejiaa@redesla.la</strong>, tendrá hasta el&nbsp;<strong>17</strong><strong>de julio del 2023 para realizar su pago con descuento&nbsp;</strong>o bien hasta el día&nbsp;<strong>17 de agosto de 2023</strong>, indicando nombre completo y paquete seleccionado. Si no sigue este paso no quedará inscrito.<br></span><span style="font-size: 10pt"><span style="color: #236fa1"><strong>4.</strong></span> Espere el correo de confirmación, en donde le diremos que su inscripción fue exitosa.<br></span><span style="font-size: 10pt"><span style="color: #236fa1"><strong>5.</strong></span> Recibirá el correo y/o mensaje de WhatsApp con los accesos al curso.</span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt">En caso de<strong> solicitar factura</strong> es importante considere que tendrá<strong> 5 días hábiles</strong> después de realizar el pago y deberá solicitarla dentro del <strong>mes en que realizo el pago</strong>, enviar su comprobante de pago y datos fiscales incluyendo el uso de CFDI y la constancia de situación fiscal al correo: pmejiaa@redesla.la</span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt; color: #236fa1"><strong>Nota: Al ser un curso-taller se LIMITA el número de participantes le recomendamos realizar su pago lo antes posible para no perder su lugar, ¡No se pierda la oportunidad de ser parte!</strong></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>Si usted desea mayores informes sobre el proceso, dejamos a continuación los medios de contacto a través de los cuales le daremos la atención debida:</strong></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>WhatsApp: +52 4425039607</strong></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>WhatsApp: +52 477 843 3415</strong></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><a href="https://wa.link/np1fm8" rel="noreferrer" target="_blank"><strong>https://wa.link/np1fm8</strong></a></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><a href="https://wa.link/c4j0hg" rel="noreferrer" target="_blank"><strong>https://wa.link/c4j0hg</strong></a></span></p>
                                                            <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt"><span style="font-size: 10pt"><strong>Teléfono: +52 427 106 7882 // +52 477 843 3415 // +52 553 798 6840</strong></span></p>
                                                            <div id="v1v1v1v1v1v1signature" style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt">-- <br>
                                                                <p><img src="https://redesla.la/cursos/info.jpg" width="370" height="96"></p>
                                                                <p>Visita nuestro sitio web: <a href="https://redesla.la" rel="noreferrer" target="_blank">https://redesla.la</a>&nbsp;</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>